
services:
  postgres:
    image: postgres:13.10
    env_file: .env                 
    volumes:
      - pg_data:/var/lib/postgresql/data  

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
    env_file: .env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    volumes:
      - static:/app/static
    env_file: .env

  gateway:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend

volumes:
  static:
  media:
  pg_data:
