services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ivanbed/kittygram_backend   
    volumes:
      - static:/app/static/back
      - media:/app/media
    env_file: .env
    depends_on:
      - postgres

  frontend:
    image: ivanbed/kittygram_frontend   
    volumes:
      - static:/app/build
    env_file: .env

  gateway:
    image: ivanbed/kittygram_gateway   
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend

volumes:
  static:
  media:
  pg_data:
